REQUEST_STATUS_PENDING = "pending_approval"
REQUEST_STATUS_APPROVED = "approved"
REQUEST_STATUS_IN_WORK = "in_work"
REQUEST_STATUS_DONE = "done"
REQUEST_STATUS_REJECTED = "rejected"
REQUEST_STATUS_RECEIVED = "received"

APPROVAL_STATUS_PENDING = "pending"
APPROVAL_STATUS_APPROVED = "approved"
APPROVAL_STATUS_REJECTED = "rejected"

APPROVAL_KIND_EXECUTOR_EXTRA = "executor_extra"
APPROVAL_KIND_LEADER_EXTRA = "leader_extra"
