services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - закупки_net

  app:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      FILES_DIR: ${FILES_DIR}
    volumes:
      - ./data/files:${FILES_DIR}
    depends_on:
      - db
    networks:
      - закупки_net

networks:
  закупки_net:
    driver: bridge

volumes:
  db_data:
